"""Done

Revision ID: 130404c24ade
Revises: 77f85d609b86
Create Date: 2024-01-23 21:26:39.505141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130404c24ade'
down_revision = '77f85d609b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('friends')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
